version: 2.0
jobs:
  build:
    docker:
      - image: norionomura/swift
        #swiftdocker/swift update test docker
      - image: mongo:3.4.4
    steps:
      - checkout
      - run:
          name: Build
          command: |
           swift package resolve
           swift build

  test:
    docker:
      - image: norionomura/swift
      - image: mongo:3.4.4
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: |
           swift test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build

