version: 2.0
jobs:
  build:
    docker:
      - image: klembara/swift4:0.0.1
      - image: mongo:3.4.4
    steps:
      - checkout

  test:
    docker:
      - image: klembara/swift4:0.0.1
      - image: mongo:3.4.4
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: |
           swift package resolve
           swift build
           swift test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build

